"""update cases table

Revision ID: 3793d57b55b2
Revises: 62a42746e91f
Create Date: 2026-09-11 16:27:13.356499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3793d57b55b2'
down_revision: Union[str, Sequence[str], None] = '62a42746e91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('field_name', sa.String(length=255), nullable=False))
    op.add_column('cases', sa.Column('department_name', sa.String(length=255), nullable=False))
    op.add_column('cases', sa.Column('agency_name', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('applicant_name', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('cases', sa.Column('officer_name', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('received_at', sa.DateTime(), nullable=False))
    op.add_column('cases', sa.Column('deadline_at', sa.DateTime(), nullable=False))
    op.add_column('cases', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('cases', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('cases', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('cases', 'status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_cases_case_code'), 'cases', ['case_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_case_code'), table_name='cases')
    op.alter_column('cases', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('cases', 'case_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('cases', 'updated_at')
    op.drop_column('cases', 'created_at')
    op.drop_column('cases', 'completed_at')
    op.drop_column('cases', 'deadline_at')
    op.drop_column('cases', 'received_at')
    op.drop_column('cases', 'officer_name')
    op.drop_column('cases', 'phone_number')
    op.drop_column('cases', 'applicant_name')
    op.drop_column('cases', 'agency_name')
    op.drop_column('cases', 'department_name')
    op.drop_column('cases', 'field_name')
    # ### end Alembic commands ###
