"""increase procedure name length

Revision ID: 608303ca76c0
Revises: 60519574f188
Create Date: 2026-09-12 00:29:29.772150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608303ca76c0'
down_revision: Union[str, Sequence[str], None] = '60519574f188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedures', 'name',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('procedures', 'name',
               existing_type=sa.Unicode(length=500),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
