"""add case foreign key relations

Revision ID: db6f0c28c9e3
Revises: 6f01205fc8b4
Create Date: 2026-09-11 22:08:52.148001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6f0c28c9e3'
down_revision: Union[str, Sequence[str], None] = '6f01205fc8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cases_department_id'), 'cases', ['department_id'], unique=False)
    op.create_index(op.f('ix_cases_officer_id'), 'cases', ['officer_id'], unique=False)
    op.create_index(op.f('ix_cases_procedure_id'), 'cases', ['procedure_id'], unique=False)
    op.create_foreign_key('fk_cases_officer_id', 'cases', 'officers', ['officer_id'], ['id'])
    op.create_foreign_key('fk_cases_department_id', 'cases', 'departments', ['department_id'], ['id'])
    op.create_foreign_key('fk_cases_procedure_id', 'cases', 'procedures', ['procedure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cases_procedure_id', 'cases', type_='foreignkey')
    op.drop_constraint('fk_cases_department_id', 'cases', type_='foreignkey')
    op.drop_constraint('fk_cases_officer_id', 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_procedure_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_officer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_department_id'), table_name='cases')
    op.drop_column('cases', 'officer_id')
    op.drop_column('cases', 'department_id')
    op.drop_column('cases', 'procedure_id')
    # ### end Alembic commands ###
